---

name: Go

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest

    # Service containers to run with `build`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
      mongodb:
        image: mongo
        options: >-
          --health-cmd "mongo --eval 'db.stats().ok' --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v

      - name: Test
        run: |
          go test ./app -v -race -coverprofile=coverage.txt -covermode=atomic
          bash <(curl -s https://codecov.io/bash)
